### ISSUE TITLE
Sample State Feedback

### ISSUE THREAD

**Issue by d-webs** [mszekalski/Hang#1]
Looks good! Just a couple things missing here. As you currently have, threads/channels/DMS should be their own slice of state. We can just call it 'threads' for short. Inside of each item in that slice of state, you will probably want some flag that indicated what type of thread it is (i.e. channel, DM). Additionally, we would want each thread item to hold an array of message_ids so we can easily reference them in the frontend.  

**Note on channels vs. DMs**: While these should live in the same slice of state, **I recommend keeping them in separate collections of ids under the users slice of state**. While you may have a slice of state simply called "threads" that holds DMs and Channels, the users should keep the ids separated-- the user should have a set of ids called directMessageIds and channelIds in order to make it easy to reference these entities.

**Comment by mszekalski** [comment]
Got it, thanks. Edited it a bit. I'm still not sure how I'm going to implement these differences between a DM and a Channel. I need to do some research on it.
